# Generated by Django 5.0.6 on 2024-05-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=60, verbose_name='Название книги')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='Автор')),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='Год изд.')),
                ('pages', models.CharField(blank=True, max_length=4, verbose_name='Страниц')),
                ('registered', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Зарегистрировано')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'книгу',
                'verbose_name_plural': 'Книги',
                'ordering': ['year'],
            },
        ),
    ]
